# Generated by Django 4.1.3 on 2023-01-26 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('22751416-9e5a-469e-a2f4-74e78544b52a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
