# Generated by Django 4.1.3 on 2023-01-09 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('477bc20c-19ee-4fe2-89ce-fd91a626b590'), editable=False, primary_key=True, serialize=False),
        ),
    ]
