# Generated by Django 4.1.3 on 2023-01-11 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0e74656-f956-4349-b5b1-d0386fa8a9aa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
