# Generated by Django 4.1.3 on 2023-01-14 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import get_outside.models.mappointModel
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mappoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(choices=[('Outdoor', 'Outdoor Activity'), ('Indoor', 'Indoor Activity'), ('Out & In', 'Outdoor and Indoor Activity')], default='Outdoor', max_length=100)),
                ('openingHours', models.JSONField(null=True)),
                ('description', models.TextField()),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('ratings', models.FloatField(max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='get_outside.category')),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=get_outside.models.mappointModel.upload_to)),
                ('mappoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='get_outside.mappoint')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePins',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_outside.mappoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mappoint_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='get_outside.mappoint')),
            ],
        ),
    ]
