# Generated by Django 4.1.3 on 2023-01-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mappoint',
            new_name='mappointPin',
        ),
    ]
