# Generated by Django 4.1.3 on 2022-12-15 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mappoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(choices=[('Outdoor', 'Outdoor Activity'), ('Indoor', 'Indoor Activity'), ('Out & In', 'Outdoor and Indoor Activity')], default='Outdoor', max_length=100)),
                ('openingHours', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.TextField()),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('ratings', models.FloatField(max_length=20)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='get_outside.category'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
