# Generated by Django 4.1.3 on 2023-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='cloud_pic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
