# Generated by Django 4.1.3 on 2023-01-25 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mappoint',
            new_name='mappointPin',
        ),
        migrations.RenameField(
            model_name='mappoint',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
