# Generated by Django 4.1.3 on 2023-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
