# Generated by Django 4.1.3 on 2023-01-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_outside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('06e05a06-cae1-46db-92c8-58881e0236e4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('452d2883-90cd-4967-a0c4-53b4a5fc2ad3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c36fe3fa-b6b3-4e82-bc4d-a727c0044cda'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ac8ac0e-fdd6-43b2-8c15-43354c1009cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
