# Generated by Django 4.1.3 on 2022-12-15 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0002_comment_mappoint_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mappoint_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='get_outside.mappoint'),
        ),
    ]
