# Generated by Django 4.1.3 on 2022-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0002_mappoint_delete_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
