# Generated by Django 4.1.3 on 2022-12-17 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import get_outside.models.mappointModel


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_outside', '0003_comment_mappoint_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='mappoint_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='get_outside.mappoint'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=get_outside.models.mappointModel.upload_to)),
                ('mappoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='get_outside.mappoint')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_outside.mappoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
