# Generated by Django 4.1.3 on 2022-12-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0003_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mappoint',
        ),
    ]
