# Generated by Django 4.1.3 on 2023-01-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappoint',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='get_outside.category'),
        ),
    ]
