# Generated by Django 4.1.3 on 2022-12-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0003_comment_mappoint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mappoint_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='get_outside.mappoint'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='openingHours',
            field=models.JSONField(),
        ),
    ]
