# Generated by Django 4.1.3 on 2023-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0004_rename_creator_id_mappoint_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='get_outside.category'),
        ),
    ]
