# Generated by Django 4.1.3 on 2023-01-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0004_remove_mappoint_picture_alter_comment_mappoint_id_and_more'),
        ('get_outside', '0005_alter_mappoint_openinghours'),
    ]

    operations = [
    ]
