# Generated by Django 4.1.3 on 2022-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0005_mappoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='category',
        ),
    ]
