# Generated by Django 4.1.3 on 2023-01-11 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0006_merge_20230109_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f494cacd-6c80-4ebb-91d6-256e9cb8b360'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('43df6056-3f2a-43bb-8cef-2a71a2efa3d7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='favoritepins',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c065ac6-da0b-4393-b9e1-3d8a3c1c2e6e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('17b5e178-9eda-4f69-80e3-40eceebc8b42'), editable=False, primary_key=True, serialize=False),
        ),
    ]
