# Generated by Django 4.1.3 on 2022-12-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_outside', '0006_remove_mappoint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='get_outside.category'),
        ),
    ]
