# Generated by Django 4.1.3 on 2022-12-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_outside', '0007_mappoint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='openingHours',
            field=models.TextField(),
        ),
    ]
