name: Docker Build and Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build Docker image
      run: docker build -t django-api .

    - name: Run Docker container
      run: docker run -p 8000:8000 django-api
