name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag django-api:$(date +%s)

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
